### ISSUE TITLE
Does FAMFS supports write now?

### ISSUE THREAD

**Issue by mycastiel** [cxl-micron-reskit/famfs#19]
When I was trying to do some simple cmds to see the behavior, I notice that if I use cmds like:
`echo 1234 >> /mnt/famfs/test`
then I am using famfs_dax_write_iter to change the contents. 
However the log is not added. Therefore, famfs verify/fsck cannot be passed.
Is that a issue? Or there is another way to write something to the file?

**Comment by arramesh42** [comment]
"Famfs create" / "famfs cp /tmp/myfile /mnt/famfs/myfile" are the options to create files in famfs.
Also you cannot update existing files in famfs, it is create once and read many times.

**Comment by jagalactic** [comment]
Hi @mycastiel. Famfs does not do "allocate on write". In order to create valid famfs files, you must use ```famfs creat``` or ```famfs cp```, and make directories via ```famfs mkdir``` (or the same api calls that the cli uses).  These operations take care of space allocation and metadata logging, and create the files in your mounted instance AND make the ioctl call to tell each file what memory it should map to.  

Basically you can access famfs files via normal tools, but you can't create them with normal tools. 

Once a famfs file is properly created, you can write, read or mmap the data through normal means. But you can't change the size of the file; if you do, famfs will treat the file as invalid. Note that a lot of standard Linux tools sometimes truncate files (e.g. ```dd```, will truncate unless you ```dd conv=notrunc```).

```famfs_dax_write_iter()``` is the kernel handler for write, but famfs files must be preallocated via ```famfs creat``` or ```famfs cp``` first in order to initialize the mapping metadata.  Once a famfs file is pre-allocated, you can call write, read and mmap on the entire range of the file, but you can't write past EOF or truncate.

Famfs currently prevents writing past EOF, but it doesn't have a way to prevent truncate. But if you truncate a file, famfs will notice and prevent further use of the file because it is in an invalid state.

If you have invalid files (such as the one created via ```echo 1234 >> /mnt/famfs/test```, it will be detected by ```famfs check /mnt/famfs```, and you can make it disappear by unmounting and remounting. 

The cli reference - https://github.com/cxl-micron-reskit/famfs/blob/master/markdown/famfs-cli-reference.md - should clarify a lot of this. Also, a lot of famfs cli usage can be observed in the smoke test files.

I hope this is helpful...

**Comment by mycastiel** [comment]
Thanks! This is really helpful.
